/* The `.js` extensions are deliberate: this file is also compiled by the
   `vite.config` TypeScript project, which uses `nodenext` resolution and requires
   them. The application's project resolves them just the same. */
import { SECTIONS } from './sections.js'
import { aSlug } from './slug.js'

/*
The routes the build has to materialise as folders.

The console is served as static files: `UseDefaultFiles()` maps `/zones/` to
`/zones/index.html` and redirects `/zones` with a 301, so that file merely existing
is enough for `dns.shlab.app/settings/logging/` to work and survive an F5. It is
the same technique any static site generator uses to publish a site without
configuring the server.

It lives in `src/` and not in `vite.config` because the list comes from `SECTIONS`:
if a new sub-section appears tomorrow, its folder is generated by itself.
*/
export const STATIC_ROUTES: string[] = SECTIONS.flatMap((s) => [
  s.id,
  ...(s.subs ?? []).map((t) => `${s.id}/${aSlug(t)}`),
])
