name: Build

on:
  push:
    branches:
      - master
    tags:
      - v**
  pull_request:

jobs:
  build:
    name: Build software
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
    steps:
      - name: Checkout code DnsServer
        uses: actions/checkout@v4

      - name: Checkout code TechnitiumLibrary
        uses: actions/checkout@v4
        with:
          repository: TechnitiumSoftware/TechnitiumLibrary
          path: TechnitiumLibrary

      - name: Define tags and metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository_owner }}/dns-server,enable=true
          flavor: |
            latest=true
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        id: docker
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true
